const USER_LOCATION = 'USER_LOCATION'
const USER_DATA = 'USER_DATA'
const AUTH_TOKEN = 'AUTH_TOKEN'

const COMPANIES = 'COMPANIES'

const ON_LOGOUT = 'ON_LOGOUT'
const CLAIM_PROJECTS = 'CLAIM_PROJECTS'
const ACTION_NEEDED_PROJECTS = 'ACTION_NEEDED_PROJECTS'

const PROJECT_ID = 'PROJECT_ID'
const PROJECT_DETAILS = 'PROJECT_DETAILS'

export {
  AUTH_TOKEN,
  USER_DATA,
  ON_LOGOUT,
  USER_LOCATION,
  COMPANIES,

  CLAIM_PROJECTS,
  ACTION_NEEDED_PROJECTS,

  PROJECT_ID,
  PROJECT_DETAILS
};
