const USER_LOCATION = 'USER_LOCATION'
const USER_DATA = 'USER_DATA'
const AUTH_TOKEN = 'AUTH_TOKEN'

const COMPANIES = 'COMPANIES'

const ON_LOGOUT = 'ON_LOGOUT'
const CLAIM_PROJECTS = 'CLAIM_PROJECTS'
const ACTION_NEEDED_PROJECTS = 'ACTION_NEEDED_PROJECTS'

const PROJECT_ID = 'PROJECT_ID'
const PROJECT_DETAILS = 'PROJECT_DETAILS'

const UNPAID_TRANSACTIONS = 'UNPAID_TRANSACTIONS'
const PAID_TRANSACTIONS = 'PAID_TRANSACTIONS'

const OPTIONS = 'OPTIONS'

const STAFF_LIST = 'STAFFLIST'
const STAFF_CURRENT = 'STAFF_CURRENT'

const FCM='FCM'
const DETAILS_TAB='DETAILS_TAB'

export {
  AUTH_TOKEN,
  USER_DATA,
  ON_LOGOUT,
  USER_LOCATION,
  COMPANIES,

  CLAIM_PROJECTS,
  ACTION_NEEDED_PROJECTS,

  PROJECT_ID,
  PROJECT_DETAILS,

  UNPAID_TRANSACTIONS,
  PAID_TRANSACTIONS,
  OPTIONS,

  STAFF_CURRENT,
  STAFF_LIST,

  FCM,
  DETAILS_TAB
};
