const USER_LOCATION = 'USER_LOCATION'
const USER_DATA = 'USER_DATA'
const AUTH_TOKEN = 'AUTH_TOKEN'

const COMPANIES = 'COMPANIES'

const ON_LOGOUT = 'ON_LOGOUT'


export {
  AUTH_TOKEN,
  USER_DATA,
  ON_LOGOUT,
  USER_LOCATION,
  COMPANIES
};
